#!/usr/bin/env python3
"""generate_anesthetic_portes_seed.py — emit migration 029 from anesthetic_portes.json.

Single source of truth: backend/internal/repository/anesthetic_portes.json.
Output: backend/db/migrations/029_cbhpm_anesthetic_portes.sql

Adds the cbhpm_codes.anesthetic_porte column and seeds it per code. Idempotent
(ADD COLUMN IF NOT EXISTS + UPDATE … WHERE code). Roadmap stage AN-1 (data only):
the engine does NOT read this column yet, so calculations are unchanged.

Run: python3 data/generate_anesthetic_portes_seed.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "backend" / "internal" / "repository" / "anesthetic_portes.json"
OUT = ROOT / "backend" / "db" / "migrations" / "029_cbhpm_anesthetic_portes.sql"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    rows = data["portes"]

    lines = [
        "-- Migration 029: Per-code anesthetic porte (AN0-AN8) — roadmap stage AN-1 (data only).",
        "--",
        "-- GENERATED by data/generate_anesthetic_portes_seed.py from",
        "-- backend/internal/repository/anesthetic_portes.json (single source of truth).",
        "-- DO NOT EDIT BY HAND — regenerate instead.",
        "--",
        "-- Source: CBHPM 2022 'N° de Porte Anest.' column (p.139 item 2 defines AN->surgical-porte",
        "-- equivalence). The engine does NOT consume this column yet (stage AN-4), so calculations",
        "-- are unchanged. Idempotent: ADD COLUMN IF NOT EXISTS + UPDATE … WHERE code.",
        "",
        "ALTER TABLE cbhpm_codes",
        "    ADD COLUMN IF NOT EXISTS anesthetic_porte SMALLINT",
        "        CHECK (anesthetic_porte BETWEEN 0 AND 8);",
        "",
    ]
    for r in rows:
        lines.append(
            f"UPDATE cbhpm_codes SET anesthetic_porte = {int(r['anesthetic_porte'])} "
            f"WHERE code = '{r['code']}';"
        )
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(rows)} UPDATEs)")


if __name__ == "__main__":
    main()
