#!/usr/bin/env python3
"""generate_code_modifiers_seed.py — emit the cbhpm_code_modifiers seed migration.

Single source of truth: backend/internal/repository/code_modifiers.json.
Output: backend/db/migrations/028_seed_cbhpm_code_modifiers.sql

Idempotent INSERT ... ON CONFLICT (cbhpm_code, specialty) DO NOTHING, so the
migration is safe to re-run and safe on a database that already has the rows.
This is roadmap stage N2 (write path). The engine does NOT consume these rows
until stage N5 — running this migration changes NO calculation result.

Run: python3 data/generate_code_modifiers_seed.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "backend" / "internal" / "repository" / "code_modifiers.json"
OUT = ROOT / "backend" / "db" / "migrations" / "028_seed_cbhpm_code_modifiers.sql"


def sql_str(value: str) -> str:
    """Quote a string for SQL, escaping single quotes."""
    return "'" + value.replace("'", "''") + "'"


def sql_val(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    return sql_str(str(value))


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    doc = data["source_document"]
    ver = data["source_version"]
    rows = data["modifiers"]

    lines = [
        "-- Migration 028: Seed normative per-code billing modifiers (roadmap stage N2).",
        "--",
        "-- GENERATED by data/generate_code_modifiers_seed.py from",
        "-- backend/internal/repository/code_modifiers.json (single source of truth, ADR-005).",
        "-- DO NOT EDIT BY HAND — regenerate instead.",
        "--",
        "-- Only CONFIRMED rules from the Manual de Coluna 3a ed. 2025, each with verbatim",
        "-- provenance. implemented_at/verified_by are NULL until clinical sign-off (stage N5).",
        "-- The engine does NOT read this table yet (stages N3/N5), so calculations are unchanged.",
        "-- Idempotent: ON CONFLICT (cbhpm_code, specialty) DO NOTHING.",
        "",
        "INSERT INTO cbhpm_code_modifiers (",
        "    cbhpm_code, specialty, billing_mode, laterality_rule, via_rule,",
        "    decrement_pct, max_quantity, supported_modifiers,",
        "    source_document, source_version, source_page, source_excerpt, confidence",
        ") VALUES",
    ]

    values = []
    for r in rows:
        supported = json.dumps(r.get("supported_modifiers", []), ensure_ascii=False)
        tup = (
            f"    ({sql_str(r['cbhpm_code'])}, {sql_str(r['specialty'])}, "
            f"{sql_str(r['billing_mode'])}, {sql_str(r.get('laterality_rule', 'NONE'))}, "
            f"{sql_str(r.get('via_rule', 'CBHPM_DEFAULT'))}, "
            f"{sql_val(r.get('decrement_pct'))}, {sql_val(r.get('max_quantity'))}, "
            f"{sql_str(supported)}::jsonb, "
            f"{sql_str(doc)}, {sql_str(ver)}, {sql_val(r.get('source_page'))}, "
            f"{sql_str(r['source_excerpt'])}, {sql_str(r['confidence'])})"
        )
        values.append(tup)

    lines.append(",\n".join(values))
    lines.append("ON CONFLICT (cbhpm_code, specialty) DO NOTHING;")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
