#!/usr/bin/env python3
"""
Generate migration 003_seed_procedures.sql from procedures.json.

Usage:
    python3 data/generate_seed.py

Output:
    backend/db/migrations/003_seed_procedures.sql

The generated file is safe to re-run against an existing database
because every INSERT uses ON CONFLICT clauses.
"""

import json
from collections import OrderedDict
from pathlib import Path

ROOT    = Path(__file__).parent.parent
CATALOG = ROOT / "backend" / "internal" / "repository" / "procedures.json"
OUT     = ROOT / "backend" / "db" / "migrations" / "003_seed_procedures.sql"


def esc(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    return s.replace("'", "''")


def main() -> None:
    data: list[dict] = json.loads(CATALOG.read_text(encoding="utf-8"))

    # ── Aggregate ─────────────────────────────────────────────────────────────
    proc_order:   list[str]         = []          # insertion order of procedure names
    proc_entries: dict[str, list]   = {}          # name → [{cbhpm_code, porte}, ...]
    proc_specialty: dict[str, str]  = {}          # name → 'NEUROSURGERY' | 'SPINE'
    cbhpm_descs:  dict[str, str]    = OrderedDict()  # code → description (first wins)
    cbhpm_aux:    dict[str, int]    = {}          # code → num_auxiliaries (first wins)

    for row in data:
        name  = row["procedure_name"]
        code  = row["cbhpm_code"]
        desc  = row["description"]
        porte = row["porte"]
        n_aux = row.get("num_auxiliaries", 0)
        # Procedure-level specialty. Only the canonical 'SPINE' marker (Manual de
        # Coluna fiches) maps to SPINE; every other value defaults to NEUROSURGERY,
        # honouring the sbn_procedures.specialty CHECK constraint.
        spec  = "SPINE" if row.get("specialty") == "SPINE" else "NEUROSURGERY"

        if name not in proc_entries:
            proc_order.append(name)
            proc_entries[name] = []
            proc_specialty[name] = spec

        if code not in cbhpm_descs:
            cbhpm_descs[code] = desc

        if code not in cbhpm_aux:
            cbhpm_aux[code] = n_aux

        # Deduplicate CBHPM codes within this procedure (keep first occurrence)
        if not any(e["cbhpm_code"] == code for e in proc_entries[name]):
            proc_entries[name].append({"cbhpm_code": code, "porte": porte})

    n_procs = len(proc_order)
    n_codes = len(cbhpm_descs)
    n_maps  = sum(len(v) for v in proc_entries.values())

    # ── SQL output ────────────────────────────────────────────────────────────
    lines: list[str] = [
        "-- Migration 003: Procedure catalog seed.",
        "-- Generated by data/generate_seed.py — do not edit by hand.",
        "-- Re-run this script after updating procedures.json to refresh the migration.",
        "-- Safe to apply to an existing database (all INSERTs use ON CONFLICT).",
        f"-- Coverage: {n_procs} SBN procedures · {n_codes} CBHPM codes · {n_maps} mappings.",
        "",
    ]

    # ── 1. CBHPM codes ────────────────────────────────────────────────────────
    lines.append("-- ── CBHPM codes ──────────────────────────────────────────────────────────────")
    lines.append("INSERT INTO cbhpm_codes (code, description, num_auxiliaries) VALUES")
    items = list(cbhpm_descs.items())
    for i, (code, desc) in enumerate(items):
        sep = "," if i < len(items) - 1 else ""
        n_aux = cbhpm_aux.get(code, 0)
        lines.append(f"    ('{esc(code)}', '{esc(desc)}', {n_aux}){sep}")
    lines.append(
        "ON CONFLICT (code) DO UPDATE SET"
        " description = EXCLUDED.description,"
        " num_auxiliaries = EXCLUDED.num_auxiliaries;"
    )
    lines.append("")

    # ── 2. SBN procedures ─────────────────────────────────────────────────────
    # SBN code is the 1-based sequential index, matching FileRepository's idFromIndex.
    lines.append("-- ── SBN procedures ───────────────────────────────────────────────────────────")
    lines.append("INSERT INTO sbn_procedures (code, name, specialty) VALUES")
    for i, name in enumerate(proc_order):
        sep = "," if i < len(proc_order) - 1 else ""
        lines.append(f"    ('{i + 1}', '{esc(name)}', '{proc_specialty[name]}'){sep}")
    lines.append(
        "ON CONFLICT (code) DO UPDATE SET"
        " name = EXCLUDED.name,"
        " specialty = EXCLUDED.specialty;"
    )
    lines.append("")

    # ── 3. Mappings ───────────────────────────────────────────────────────────
    lines.append("-- ── SBN → CBHPM mappings ─────────────────────────────────────────────────────")
    for idx, name in enumerate(proc_order):
        sbn_code = str(idx + 1)
        for sort_order, entry in enumerate(proc_entries[name], start=1):
            cbhpm_code = entry["cbhpm_code"]
            porte      = entry["porte"]
            lines += [
                "INSERT INTO sbn_cbhpm_mappings"
                " (sbn_procedure_id, cbhpm_code_id, porte_code, sort_order)",
                f"SELECT sp.id, cc.id, '{esc(porte)}', {sort_order}",
                "FROM   sbn_procedures sp, cbhpm_codes cc",
                f"WHERE  sp.code = '{esc(sbn_code)}' AND cc.code = '{esc(cbhpm_code)}'",
                "ON CONFLICT (sbn_procedure_id, cbhpm_code_id) DO NOTHING;",
            ]
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"✓  {OUT.relative_to(ROOT)}\n"
        f"   {n_procs} SBN procedures · {n_codes} CBHPM codes · {n_maps} mappings"
    )


if __name__ == "__main__":
    main()
