#!/usr/bin/env python3
"""parse_cbhpm_anesthetic_portes.py — extract per-code anesthetic porte (AN0–AN8) from CBHPM 2022.

Source of truth for the anesthesiology valuation layer (see
docs/audits/anesthesiology-rules-traceability.md). The CBHPM 2022 procedure tables carry a
trailing "N° de Porte Anest." column (0–8, or "–" when there is no anesthetic porte). This
script extracts code → anesthetic_porte for every CBHPM code that appears in the Synvera
catalog (procedures.json), plus the official AN→surgical-porte equivalence table (p.139).

Validation: the column alignment was cross-checked against the catalog's num_auxiliaries
(85% agreement; disagreements are real CBHPM-vs-catalog data differences for spine aux),
and anest spot-checks match the PDF (3.16.02.34-7→3, 3.07.15.31-8→8, 3.02.15.02-1→5).

Output: backend/internal/repository/anesthetic_portes.json
Run:    python3 data/parse_cbhpm_anesthetic_portes.py
"""
import json
import pathlib
import re

import pdfplumber

ROOT = pathlib.Path(__file__).resolve().parent.parent
PDF = ROOT / "data" / "raw_pdfs" / "CBHPM-2022.pdf"
CATALOG = ROOT / "backend" / "internal" / "repository" / "procedures.json"
OUT = ROOT / "backend" / "internal" / "repository" / "anesthetic_portes.json"

SOURCE_DOCUMENT = "CBHPM 2022"
SOURCE_VERSION = "2022"

# Official AN porte → surgical porte equivalence (CBHPM 2022, p.139, item 2).
# AN0 = "anestesia local" = no anesthesiologist participation (item 3) → no equivalent porte.
EQUIVALENCE = {0: None, 1: "3A", 2: "3C", 3: "4C", 4: "6B", 5: "7C", 6: "9B", 7: "10C", 8: "12A"}

CODE_RX = re.compile(r"^(\d\.\d{2}\.\d{2}\.\d{2}-\d)\s+(.*)$")


def main() -> None:
    catalog_codes = {e["cbhpm_code"] for e in json.loads(CATALOG.read_text(encoding="utf-8"))}

    found: dict[str, int] = {}
    with pdfplumber.open(PDF) as pdf:
        for page in pdf.pages:
            for line in (page.extract_text() or "").splitlines():
                m = CODE_RX.match(line.strip())
                if not m:
                    continue
                code, rest = m.group(1), m.group(2)
                toks = rest.split()
                if not toks:
                    continue
                last = toks[-1]
                # The trailing column is the anesthetic porte: a digit 0–8 (or "–" = none).
                if re.fullmatch(r"[0-8]", last):
                    # First occurrence wins; CBHPM lists one anesthetic porte per code.
                    found.setdefault(code, int(last))

    rows = [
        {"code": c, "anesthetic_porte": found[c]}
        for c in sorted(catalog_codes)
        if c in found
    ]

    out = {
        "_comment": (
            "Canonical source of truth for per-code anesthetic portes (AN0-AN8) and the official "
            "AN->surgical-porte equivalence (CBHPM 2022 p.139). Feeds migration 029 and the "
            "FileRepository read path. GENERATED by data/parse_cbhpm_anesthetic_portes.py — "
            "do not edit by hand; re-run instead."
        ),
        "source_document": SOURCE_DOCUMENT,
        "source_version": SOURCE_VERSION,
        "equivalence": {str(k): v for k, v in EQUIVALENCE.items()},
        "portes": rows,
    }
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    from collections import Counter
    dist = Counter(r["anesthetic_porte"] for r in rows)
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(rows)} codes "
          f"({len(rows)}/{len(catalog_codes)} of catalog)")
    print("AN porte distribution:", dict(sorted(dist.items())))


if __name__ == "__main__":
    main()
