// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calculation struct {
	ID                    pgtype.UUID
	PublicID              pgtype.UUID
	PhysicianID           pgtype.UUID
	CbhpmVersionID        pgtype.UUID
	ProcedureName         string
	ProcedureSbnCode      pgtype.Text
	SelectedCbhpmCodes    []byte
	Adjustments           []byte
	AccessRoute           string
	AuxiliariesCount      int32
	RequiresAnesthesia    bool
	SurgeonValue          pgtype.Numeric
	AuxiliariesTotalValue pgtype.Numeric
	AnesthesiologistValue pgtype.Numeric
	TeamTotalValue        pgtype.Numeric
	CalculationBreakdown  []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type CbhpmCode struct {
	ID                pgtype.UUID
	Code              string
	Description       string
	NumAuxiliaries    int16
	BillingMode       string
	Specialty         string
	LateralitySupport bool
	CreatedAt         pgtype.Timestamptz
}

type CbhpmVersion struct {
	ID        pgtype.UUID
	Code      string
	Label     string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type Composition struct {
	ID                 pgtype.UUID
	PublicID           pgtype.UUID
	PhysicianID        pgtype.UUID
	Name               string
	SbnProcedureID     pgtype.Text
	SbnProcedureName   string
	SelectedCodes      []byte
	AccessRouteType    string
	AuxiliariesCount   int32
	RequiresAnesthesia bool
	Adjustments        []byte
	Modifiers          []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type PhysicianAccount struct {
	ID                 pgtype.UUID
	ClerkUserID        string
	Email              pgtype.Text
	Name               pgtype.Text
	PlanType           string
	SubscriptionStatus string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Porte struct {
	Code     string
	ValueBrl pgtype.Numeric
}

type PorteValue struct {
	ID             pgtype.UUID
	CbhpmVersionID pgtype.UUID
	Porte          string
	ValueBrl       pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
}

type SbnCbhpmMapping struct {
	ID             pgtype.UUID
	SbnProcedureID pgtype.UUID
	CbhpmCodeID    pgtype.UUID
	PorteCode      string
	SortOrder      int32
	CreatedAt      pgtype.Timestamptz
}

type SbnProcedure struct {
	ID                pgtype.UUID
	Code              string
	Name              string
	Description       pgtype.Text
	BillingMode       string
	Specialty         string
	LateralitySupport bool
	CreatedAt         pgtype.Timestamptz
}

type SpineProcedureMetadatum struct {
	ID                pgtype.UUID
	SbnProcedureID    pgtype.UUID
	VertebralRegion   pgtype.Text
	SurgicalApproach  pgtype.Text
	FusionStatus      pgtype.Text
	ImplantCategory   pgtype.Text
	OsteoporosisAware pgtype.Bool
	ClinicalContext   pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
