// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calculation struct {
	ID                    pgtype.UUID
	ProcedureName         string
	ProcedureSbnCode      pgtype.Text
	SurgeonValue          pgtype.Numeric
	AuxiliariesTotalValue pgtype.Numeric
	AnesthesiologistValue pgtype.Numeric
	TeamTotalValue        pgtype.Numeric
	AuxiliariesCount      pgtype.Int2
	RequiresAnesthesia    pgtype.Bool
	AccessRoute           pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type CalculationModifier struct {
	ID                pgtype.UUID
	CalculationID     pgtype.UUID
	QuantitySelected  pgtype.Int4
	Laterality        pgtype.Text
	VertebralRegion   pgtype.Text
	SurgicalApproach  pgtype.Text
	FusionStatus      pgtype.Text
	ImplantCategory   pgtype.Text
	OsteoporosisAware pgtype.Bool
	ClinicalContext   pgtype.Text
	CreatedAt         pgtype.Timestamptz
}

type CbhpmCode struct {
	ID                pgtype.UUID
	Code              string
	Description       string
	NumAuxiliaries    int16
	BillingMode       string
	Specialty         string
	LateralitySupport bool
	CreatedAt         pgtype.Timestamptz
}

type Composition struct {
	ID                 pgtype.UUID
	PhysicianID        pgtype.UUID
	SbnProcedureID     pgtype.UUID
	Name               string
	Adjustments        []byte
	AuxiliariesCount   int16
	RequiresAnesthesia bool
	AccessRouteType    pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type CompositionModifier struct {
	ID                pgtype.UUID
	CompositionID     pgtype.UUID
	QuantitySelected  pgtype.Int4
	Laterality        pgtype.Text
	VertebralRegion   pgtype.Text
	SurgicalApproach  pgtype.Text
	FusionStatus      pgtype.Text
	ImplantCategory   pgtype.Text
	OsteoporosisAware pgtype.Bool
	ClinicalContext   pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PhysicianAccount struct {
	ID          pgtype.UUID
	ClerkUserID string
	Email       pgtype.Text
	Name        pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Porte struct {
	Code     string
	ValueBrl pgtype.Numeric
}

type SbnCbhpmMapping struct {
	ID             pgtype.UUID
	SbnProcedureID pgtype.UUID
	CbhpmCodeID    pgtype.UUID
	PorteCode      string
	SortOrder      int32
	CreatedAt      pgtype.Timestamptz
}

type SbnProcedure struct {
	ID                pgtype.UUID
	Code              string
	Name              string
	Description       pgtype.Text
	BillingMode       string
	Specialty         string
	LateralitySupport bool
	CreatedAt         pgtype.Timestamptz
}

type SpineProcedureMetadatum struct {
	ID                pgtype.UUID
	SbnProcedureID    pgtype.UUID
	VertebralRegion   pgtype.Text
	SurgicalApproach  pgtype.Text
	FusionStatus      pgtype.Text
	ImplantCategory   pgtype.Text
	OsteoporosisAware pgtype.Bool
	ClinicalContext   pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}
