// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPorteValue = `-- name: GetPorteValue :one
SELECT code, value_brl
FROM portes
WHERE code = $1
`

func (q *Queries) GetPorteValue(ctx context.Context, code string) (Porte, error) {
	row := q.db.QueryRow(ctx, getPorteValue, code)
	var i Porte
	err := row.Scan(&i.Code, &i.ValueBrl)
	return i, err
}

const getProcedureByID = `-- name: GetProcedureByID :one
SELECT id::text, name
FROM sbn_procedures
WHERE id = $1::uuid
`

type GetProcedureByIDRow struct {
	ID   string
	Name string
}

func (q *Queries) GetProcedureByID(ctx context.Context, id pgtype.UUID) (GetProcedureByIDRow, error) {
	row := q.db.QueryRow(ctx, getProcedureByID, id)
	var i GetProcedureByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getProcedureCodes = `-- name: GetProcedureCodes :many
SELECT
    cc.code,
    cc.description,
    m.porte_code AS porte,
    COALESCE(cc.num_auxiliaries, 0) AS num_auxiliaries,
    COALESCE(cc.billing_mode, 'PER_PROCEDURE'::text) AS billing_mode,
    COALESCE(cc.specialty, 'NEUROSURGERY'::text) AS specialty,
    COALESCE(cc.laterality_support, false) AS laterality_support
FROM sbn_cbhpm_mappings m
JOIN cbhpm_codes cc ON cc.id = m.cbhpm_code_id
WHERE m.sbn_procedure_id = $1::uuid
ORDER BY m.sort_order, cc.code
`

type GetProcedureCodesRow struct {
	Code              string
	Description       string
	Porte             string
	NumAuxiliaries    int16
	BillingMode       string
	Specialty         string
	LateralitySupport bool
}

func (q *Queries) GetProcedureCodes(ctx context.Context, sbnProcedureID pgtype.UUID) ([]GetProcedureCodesRow, error) {
	rows, err := q.db.Query(ctx, getProcedureCodes, sbnProcedureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProcedureCodesRow
	for rows.Next() {
		var i GetProcedureCodesRow
		if err := rows.Scan(
			&i.Code,
			&i.Description,
			&i.Porte,
			&i.NumAuxiliaries,
			&i.BillingMode,
			&i.Specialty,
			&i.LateralitySupport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProcedures = `-- name: SearchProcedures :many

SELECT id, name
FROM (
    SELECT DISTINCT ON (sp.id)
        sp.id::text AS id,
        sp.name,
        CASE
            WHEN unaccent(lower(sp.name)) ILIKE unaccent(lower($1)) || '%'   THEN 0
            WHEN unaccent(lower(sp.name)) ILIKE '%' || unaccent(lower($1)) || '%' THEN 1
            ELSE 2
        END AS relevance
    FROM sbn_procedures sp
    LEFT JOIN sbn_cbhpm_mappings m  ON m.sbn_procedure_id = sp.id
    LEFT JOIN cbhpm_codes cc        ON cc.id = m.cbhpm_code_id
    WHERE
        unaccent(lower(sp.name))           ILIKE '%' || unaccent(lower($1)) || '%'
        OR unaccent(lower(cc.code))        ILIKE '%' || unaccent(lower($1)) || '%'
        OR unaccent(lower(cc.description)) ILIKE '%' || unaccent(lower($1)) || '%'
    ORDER BY sp.id
) sub
ORDER BY relevance, name
LIMIT 20
`

type SearchProceduresRow struct {
	ID   string
	Name string
}

// Queries for the Synvera domain model (sbn_procedures → sbn_cbhpm_mappings → cbhpm_codes).
// These are the canonical queries used by PostgresRepository.
// If sqlc codegen is wired into CI, these become the source of truth for generated types.
// Returns up to 20 SBN procedures matching the query, ordered by relevance:
//
//	0 = procedure name starts with the query (strongest signal)
//	1 = procedure name contains the query
//	2 = match is only in a CBHPM code or description
//
// The trigram indexes on unaccent(lower(name)) and unaccent(lower(description))
// (created in migration 004) make the ILIKE patterns sub-millisecond on Neon.
func (q *Queries) SearchProcedures(ctx context.Context, query string) ([]SearchProceduresRow, error) {
	rows, err := q.db.Query(ctx, searchProcedures, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProceduresRow
	for rows.Next() {
		var i SearchProceduresRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
