// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompositionsByPhysician = `-- name: CountCompositionsByPhysician :one
SELECT COUNT(*)::int AS composition_count
FROM compositions
WHERE physician_id = $1::uuid
`

// Returns the number of compositions owned by the given physician.
// Used by the plan-limit enforcement layer to check FREE_COMPOSITIONS_LIMIT.
func (q *Queries) CountCompositionsByPhysician(ctx context.Context, physicianID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCompositionsByPhysician, physicianID)
	var composition_count int32
	err := row.Scan(&composition_count)
	return composition_count, err
}

const getActivePorteVersion = `-- name: GetActivePorteVersion :one
SELECT id::text, code, label, is_active, created_at
FROM cbhpm_versions
WHERE is_active = TRUE
LIMIT 1
`

type GetActivePorteVersionRow struct {
	ID        string
	Code      string
	Label     string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

// Returns the currently-active CBHPM version record.
// Errors when no active version exists (uix_cbhpm_versions_active guarantees at most one).
func (q *Queries) GetActivePorteVersion(ctx context.Context) (GetActivePorteVersionRow, error) {
	row := q.db.QueryRow(ctx, getActivePorteVersion)
	var i GetActivePorteVersionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCBHPMVersionByCode = `-- name: GetCBHPMVersionByCode :one
SELECT id::text, code, label, is_active, created_at
FROM cbhpm_versions
WHERE code = $1
`

type GetCBHPMVersionByCodeRow struct {
	ID        string
	Code      string
	Label     string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

// Returns a CBHPM version by its short code (e.g. "2025-2026").
func (q *Queries) GetCBHPMVersionByCode(ctx context.Context, code string) (GetCBHPMVersionByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCBHPMVersionByCode, code)
	var i GetCBHPMVersionByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPorteValue = `-- name: GetPorteValue :one
SELECT code, value_brl
FROM portes
WHERE code = $1
`

func (q *Queries) GetPorteValue(ctx context.Context, code string) (Porte, error) {
	row := q.db.QueryRow(ctx, getPorteValue, code)
	var i Porte
	err := row.Scan(&i.Code, &i.ValueBrl)
	return i, err
}

const getPorteValuesByVersion = `-- name: GetPorteValuesByVersion :many
SELECT porte, value_brl
FROM porte_values
WHERE cbhpm_version_id = $1::uuid
ORDER BY porte
`

type GetPorteValuesByVersionRow struct {
	Porte    string
	ValueBrl pgtype.Numeric
}

// Returns all porte→value_brl pairs for the given CBHPM version.
func (q *Queries) GetPorteValuesByVersion(ctx context.Context, cbhpmVersionID pgtype.UUID) ([]GetPorteValuesByVersionRow, error) {
	rows, err := q.db.Query(ctx, getPorteValuesByVersion, cbhpmVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPorteValuesByVersionRow
	for rows.Next() {
		var i GetPorteValuesByVersionRow
		if err := rows.Scan(&i.Porte, &i.ValueBrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcedureByID = `-- name: GetProcedureByID :one
SELECT
    id::text,
    name,
    COALESCE(source_document, '') AS source_document,
    COALESCE(source_version, '')  AS source_version
FROM sbn_procedures
WHERE id = $1::uuid
`

type GetProcedureByIDRow struct {
	ID             string
	Name           string
	SourceDocument string
	SourceVersion  string
}

func (q *Queries) GetProcedureByID(ctx context.Context, id pgtype.UUID) (GetProcedureByIDRow, error) {
	row := q.db.QueryRow(ctx, getProcedureByID, id)
	var i GetProcedureByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceDocument,
		&i.SourceVersion,
	)
	return i, err
}

const getProcedureCodes = `-- name: GetProcedureCodes :many
SELECT
    cc.code,
    cc.description,
    m.porte_code AS porte,
    COALESCE(cc.num_auxiliaries, 0) AS num_auxiliaries,
    COALESCE(cc.billing_mode, 'PER_PROCEDURE'::text) AS billing_mode,
    COALESCE(cc.specialty, 'NEUROSURGERY'::text) AS specialty,
    COALESCE(cc.laterality_support, false) AS laterality_support
FROM sbn_cbhpm_mappings m
JOIN cbhpm_codes cc ON cc.id = m.cbhpm_code_id
WHERE m.sbn_procedure_id = $1::uuid
ORDER BY m.sort_order, cc.code
`

type GetProcedureCodesRow struct {
	Code              string
	Description       string
	Porte             string
	NumAuxiliaries    int16
	BillingMode       string
	Specialty         string
	LateralitySupport bool
}

func (q *Queries) GetProcedureCodes(ctx context.Context, sbnProcedureID pgtype.UUID) ([]GetProcedureCodesRow, error) {
	rows, err := q.db.Query(ctx, getProcedureCodes, sbnProcedureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProcedureCodesRow
	for rows.Next() {
		var i GetProcedureCodesRow
		if err := rows.Scan(
			&i.Code,
			&i.Description,
			&i.Porte,
			&i.NumAuxiliaries,
			&i.BillingMode,
			&i.Specialty,
			&i.LateralitySupport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProcedures = `-- name: SearchProcedures :many

SELECT id, name
FROM (
    SELECT DISTINCT ON (sp.id)
        sp.id::text AS id,
        sp.name,
        CASE
            WHEN unaccent(lower(sp.name)) ILIKE unaccent(lower($1)) || '%'   THEN 0
            WHEN unaccent(lower(sp.name)) ILIKE '%' || unaccent(lower($1)) || '%' THEN 1
            ELSE 2
        END AS relevance
    FROM sbn_procedures sp
    LEFT JOIN sbn_cbhpm_mappings m  ON m.sbn_procedure_id = sp.id
    LEFT JOIN cbhpm_codes cc        ON cc.id = m.cbhpm_code_id
    WHERE
        unaccent(lower(sp.name))           ILIKE '%' || unaccent(lower($1)) || '%'
        OR unaccent(lower(cc.code))        ILIKE '%' || unaccent(lower($1)) || '%'
        OR unaccent(lower(cc.description)) ILIKE '%' || unaccent(lower($1)) || '%'
    ORDER BY sp.id
) sub
ORDER BY relevance, name
LIMIT 20
`

type SearchProceduresRow struct {
	ID   string
	Name string
}

// Queries for the Synvera domain model (sbn_procedures → sbn_cbhpm_mappings → cbhpm_codes).
// These are the canonical queries used by PostgresRepository.
// If sqlc codegen is wired into CI, these become the source of truth for generated types.
// Returns up to 20 SBN procedures matching the query, ordered by relevance:
//
//	0 = procedure name starts with the query (strongest signal)
//	1 = procedure name contains the query
//	2 = match is only in a CBHPM code or description
//
// The trigram indexes on unaccent(lower(name)) and unaccent(lower(description))
// (created in migration 004) make the ILIKE patterns sub-millisecond on Neon.
func (q *Queries) SearchProcedures(ctx context.Context, query string) ([]SearchProceduresRow, error) {
	rows, err := q.db.Query(ctx, searchProcedures, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProceduresRow
	for rows.Next() {
		var i SearchProceduresRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
